server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Access-Control-Allow-Origin "https://storybook.jakoblui.com" always;
        add_header Access-Control-Allow-Credentials "true" always;
        add_header Vary "Origin" always;
    }
}