name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm exec playwright install --with-deps chromium
      - run: pnpm run lint
      - run: pnpm run test
